name: Deploy branch
on: push

jobs:
  deploy:
    name: "butt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: echo ${{github.event}}
